name = "Adrenaline"
author = "UltraStorm"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a2c361a396f618bee9c14c101f71190202f59bd49ad34987ca16412b1b97723"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
